"""Mensaje

Revision ID: 72afaa02e1fd
Revises: 
Create Date: 2025-05-07 18:25:22.728662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72afaa02e1fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
